### ISSUE TITLE
Mismatch in readme

### ISSUE THREAD

**Issue by davidnicholai** [rinne/node-unixpass#1]
Hi, I believe your
`// Returns true if password matches hash, false otherwise
up.hash('mypassword', '$1$saltsalt$dfhjlwheucnsdicbnwuibnwicb');`
should be
`up.check(...);`
in your README both in GitHub and npm

Thank you for this library btw!

**Comment by rdominy** [comment]
Similarly in the README:
`// Returns a password hash with autogenerated salt using SHA512`
`up.hash('mypassword');`

should be
`up.mkpass('mypassword');`

**Comment by rinne** [comment]
Fixed in 1.0.3. Thanks.
